name: ci-cowsay
on: [push, workflow_dispatch]

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write     # OIDC ל-ECR (אם משתמשים)
    env:
      IMAGE_NAME: cowsay
      TAG: ${{ github.sha }}
      SMOKE_TEXT: "CI is green"
      # מעתיקים את הסודות ל-env (יהיו ריקים אם לא הוגדרו)
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN:   ${{ secrets.DOCKERHUB_TOKEN }}
      AWS_ACCOUNT_ID:    ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_REGION:        ${{ secrets.AWS_REGION }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    steps:
      - uses: actions/checkout@v4

      # Build & Package
      - name: Build image
        run: docker build -t $IMAGE_NAME:$TAG -t $IMAGE_NAME:latest .

      # Run & Test (Smoke)
      - name: Smoke test
        run: |
          out=$(docker run --rm $IMAGE_NAME:$TAG "$SMOKE_TEXT" || true)
          echo "$out" | grep -q "$SMOKE_TEXT"

      - name: Package image
        run: docker save $IMAGE_NAME:$TAG | gzip > image.tar.gz

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-image
          path: image.tar.gz
          retention-days: 7

      # Publish to Docker Hub — רק אם זה main ויש סודות
      - name: Login & push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' && env.DOCKERHUB_USERNAME != '' && env.DOCKERHUB_TOKEN != '' }}
        run: |
          echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker tag $IMAGE_NAME:$TAG "$DOCKERHUB_USERNAME/$IMAGE_NAME:latest"
          docker push "$DOCKERHUB_USERNAME/$IMAGE_NAME:latest"

      # Publish to ECR — רק אם זה main ויש סודות
      - name: Configure AWS (OIDC)
        if: ${{ github.ref == 'refs/heads/main' && env.AWS_REGION != '' && env.AWS_ROLE_TO_ASSUME != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}

      - name: Login & push to ECR
        if: ${{ github.ref == 'refs/heads/main' && env.AWS_ACCOUNT_ID != '' && env.AWS_REGION != '' && env.AWS_ROLE_TO_ASSUME != '' }}
        run: |
          REPO=$IMAGE_NAME
          REG="$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
          aws ecr describe-repositories --repository-names "$REPO" >/dev/null 2>&1 || aws ecr create-repository --repository-name "$REPO" >/dev/null
          aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$REG"
          docker tag $IMAGE_NAME:$TAG "$REG/$REPO:latest"
          docker push "$REG/$REPO:latest"
